// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/featuregate"
)

var ExporterElasticsearchEarlyEncodingWithPersistentQueueFeatureGate = featuregate.GlobalRegistry().MustRegister(
	"exporter.elasticsearch.earlyEncodingWithPersistentQueue",
	featuregate.StageAlpha,
	featuregate.WithRegisterDescription("When enabled, the exporter encodes records at ingest time and stores the already-encoded bulk items in the persistent sending queue (sending_queue.storage) instead of pdata. Only the written format is affected; both formats are always readable on drain, so toggling the gate never requires draining the queue — only downgrading the collector does. No effect without a persistent queue or when metadata_keys is configured."),
	featuregate.WithRegisterReferenceURL("https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/49835"),
	featuregate.WithRegisterFromVersion("v0.158.0"),
)
